CREATE TABLE [dbo].[CovidDeaths]
(
[iso_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[continent] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date] [datetime] NULL,
[population] [float] NULL,
[total_cases] [float] NULL,
[new_cases] [float] NULL,
[new_cases_smoothed] [float] NULL,
[total_deaths] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_deaths] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_deaths_smoothed] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_cases_per_million] [float] NULL,
[new_cases_per_million] [float] NULL,
[new_cases_smoothed_per_million] [float] NULL,
[total_deaths_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_deaths_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_deaths_smoothed_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reproduction_rate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icu_patients] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icu_patients_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hosp_patients] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hosp_patients_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weekly_icu_admissions] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weekly_icu_admissions_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weekly_hosp_admissions] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weekly_hosp_admissions_per_million] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
